// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/invoice.proto

package invoice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId string `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Amount   string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status   string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InvoiceOutput) Reset() {
	*x = InvoiceOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_invoice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvoiceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceOutput) ProtoMessage() {}

func (x *InvoiceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceOutput.ProtoReflect.Descriptor instead.
func (*InvoiceOutput) Descriptor() ([]byte, []int) {
	return file_proto_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *InvoiceOutput) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *InvoiceOutput) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *InvoiceOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type InvoiceInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId string `protobuf:"bytes,1,opt,name=invoiceId,proto3" json:"invoiceId,omitempty"`
}

func (x *InvoiceInput) Reset() {
	*x = InvoiceInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_invoice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvoiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceInput) ProtoMessage() {}

func (x *InvoiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_invoice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceInput.ProtoReflect.Descriptor instead.
func (*InvoiceInput) Descriptor() ([]byte, []int) {
	return file_proto_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *InvoiceInput) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

var File_proto_invoice_proto protoreflect.FileDescriptor

var file_proto_invoice_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x0d,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c, 0x0a, 0x0c, 0x49, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x32, 0x4b, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_invoice_proto_rawDescOnce sync.Once
	file_proto_invoice_proto_rawDescData = file_proto_invoice_proto_rawDesc
)

func file_proto_invoice_proto_rawDescGZIP() []byte {
	file_proto_invoice_proto_rawDescOnce.Do(func() {
		file_proto_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_invoice_proto_rawDescData)
	})
	return file_proto_invoice_proto_rawDescData
}

var file_proto_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_invoice_proto_goTypes = []interface{}{
	(*InvoiceOutput)(nil), // 0: proto.InvoiceOutput
	(*InvoiceInput)(nil),  // 1: proto.InvoiceInput
}
var file_proto_invoice_proto_depIdxs = []int32{
	1, // 0: proto.InvoiceService.GetInvoice:input_type -> proto.InvoiceInput
	0, // 1: proto.InvoiceService.GetInvoice:output_type -> proto.InvoiceOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_invoice_proto_init() }
func file_proto_invoice_proto_init() {
	if File_proto_invoice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_invoice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvoiceOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_invoice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvoiceInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_invoice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_invoice_proto_goTypes,
		DependencyIndexes: file_proto_invoice_proto_depIdxs,
		MessageInfos:      file_proto_invoice_proto_msgTypes,
	}.Build()
	File_proto_invoice_proto = out.File
	file_proto_invoice_proto_rawDesc = nil
	file_proto_invoice_proto_goTypes = nil
	file_proto_invoice_proto_depIdxs = nil
}
