version: '3.8'

services:
  app:
    ports:
      - "3000"
    build:
      context: ./../../
      dockerfile: ./ops/docker/Dockerfile
      target: application
    volumes:
      - ./../../:/app:rw
    environment:
      # Database envs
      DB_DATABASE: db
      DB_HOST: db
      DB_PASSWORD: db
      DB_PORT: 5432
      DB_USERNAME: db

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: db
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: db
      POSTGRES_DATABASE: db
    ports:
      - "5432"
